Open5GS daemon v2.6.6-9-ge108d62

10/13 08:09:21.690: [app] INFO: Configuration: '/home/mike/Project/open5gs/ogs_install/etc/open5gs/upf.yaml' (../lib/app/ogs-init.c:126)
10/13 08:09:21.690: [app] INFO: File Logging: '/home/mike/Project/open5gs/ogs_install/var/log/open5gs/upf.log' (../lib/app/ogs-init.c:129)
10/13 08:09:21.756: [metrics] INFO: metrics_server() [http://127.0.0.1]:3332 (../lib/metrics/prometheus/context.c:299)
10/13 08:09:21.756: [pfcp] INFO: pfcp_server() [127.0.0.1]:3330 (../lib/pfcp/path.c:30)
10/13 08:09:21.756: [gtp] INFO: gtp_server() [127.0.0.1]:3331 (../lib/gtp/path.c:30)
10/13 08:09:21.757: [app] INFO: UPF initialize...done (../src/upf/app.c:31)
10/13 08:27:11.192: [app] INFO: SIGINT received (../src/main.c:53)
10/13 08:27:11.192: [app] INFO: Open5GS daemon terminating... (../src/main.c:226)
10/13 08:27:11.194: [app] INFO: UPF terminate...done (../src/upf/app.c:39)
Open5GS daemon v2.6.6-9-ge108d62

10/13 08:30:57.588: [app] INFO: Configuration: '/home/mike/Project/open5gs/ogs_install/etc/open5gs/upf.yaml' (../lib/app/ogs-init.c:126)
10/13 08:30:57.588: [app] INFO: File Logging: '/home/mike/Project/open5gs/ogs_install/var/log/open5gs/upf.log' (../lib/app/ogs-init.c:129)
10/13 08:30:57.657: [metrics] INFO: metrics_server() [http://127.0.0.1]:3332 (../lib/metrics/prometheus/context.c:299)
10/13 08:30:57.657: [pfcp] INFO: pfcp_server() [127.0.0.1]:3330 (../lib/pfcp/path.c:30)
10/13 08:30:57.657: [gtp] INFO: gtp_server() [127.0.0.1]:3331 (../lib/gtp/path.c:30)
10/13 08:30:57.658: [app] INFO: UPF initialize...done (../src/upf/app.c:31)
10/14 01:26:02.472: [app] INFO: SIGINT received (../src/main.c:53)
10/14 01:26:02.486: [app] INFO: Open5GS daemon terminating... (../src/main.c:226)
10/14 01:26:02.634: [app] INFO: UPF terminate...done (../src/upf/app.c:39)
Open5GS daemon v2.6.6-9-ge108d62

10/14 01:26:04.484: [app] INFO: Configuration: '/home/mike/Project/open5gs/ogs_install/etc/open5gs/upf.yaml' (../lib/app/ogs-init.c:126)
10/14 01:26:04.484: [app] INFO: File Logging: '/home/mike/Project/open5gs/ogs_install/var/log/open5gs/upf.log' (../lib/app/ogs-init.c:129)
10/14 01:26:04.550: [metrics] INFO: metrics_server() [http://127.0.0.1]:3332 (../lib/metrics/prometheus/context.c:299)
10/14 01:26:04.550: [pfcp] INFO: pfcp_server() [127.0.0.1]:3330 (../lib/pfcp/path.c:30)
10/14 01:26:04.550: [gtp] INFO: gtp_server() [127.0.0.1]:3331 (../lib/gtp/path.c:30)
10/14 01:26:04.552: [app] INFO: UPF initialize...done (../src/upf/app.c:31)
Open5GS daemon v2.6.6-9-ge108d62

10/14 01:38:25.047: [app] INFO: Configuration: '/home/mike/Project/open5gs/ogs_install/etc/open5gs/upf.yaml' (../lib/app/ogs-init.c:126)
10/14 01:38:25.047: [app] INFO: File Logging: '/home/mike/Project/open5gs/ogs_install/var/log/open5gs/upf.log' (../lib/app/ogs-init.c:129)
10/14 01:38:25.108: [metrics] INFO: metrics_server() [http://127.0.0.1]:3332 (../lib/metrics/prometheus/context.c:299)
10/14 01:38:25.108: [pfcp] INFO: pfcp_server() [127.0.0.1]:3330 (../lib/pfcp/path.c:30)
10/14 01:38:25.108: [gtp] INFO: gtp_server() [127.0.0.1]:3331 (../lib/gtp/path.c:30)
10/14 01:38:25.109: [app] INFO: UPF initialize...done (../src/upf/app.c:31)
10/14 01:38:28.767: [app] INFO: SIGINT received (../src/main.c:53)
10/14 01:38:28.767: [app] INFO: Open5GS daemon terminating... (../src/main.c:226)
10/14 01:38:28.769: [app] INFO: UPF terminate...done (../src/upf/app.c:39)
Open5GS daemon v2.6.6-9-ge108d62

10/14 01:38:30.407: [app] INFO: Configuration: '/home/mike/Project/open5gs/ogs_install/etc/open5gs/upf.yaml' (../lib/app/ogs-init.c:126)
10/14 01:38:30.407: [app] INFO: File Logging: '/home/mike/Project/open5gs/ogs_install/var/log/open5gs/upf.log' (../lib/app/ogs-init.c:129)
10/14 01:38:30.485: [metrics] INFO: metrics_server() [http://127.0.0.1]:3332 (../lib/metrics/prometheus/context.c:299)
10/14 01:38:30.485: [pfcp] INFO: pfcp_server() [127.0.0.1]:3330 (../lib/pfcp/path.c:30)
10/14 01:38:30.485: [gtp] INFO: gtp_server() [127.0.0.1]:3331 (../lib/gtp/path.c:30)
10/14 01:38:30.486: [app] INFO: UPF initialize...done (../src/upf/app.c:31)
10/14 01:39:52.058: [pfcp] INFO: ogs_pfcp_connect() [127.0.0.1]:8805 (../lib/pfcp/path.c:61)
10/14 01:39:52.058: [upf] INFO: PFCP associated [127.0.0.1]:8805 (../src/upf/pfcp-sm.c:184)
10/14 01:42:13.716: [upf] WARNING: PFCP[REQ] has already been associated [127.0.0.1]:8805 (../src/upf/pfcp-sm.c:270)
10/14 01:42:13.721: [pfcp] ERROR: Remote PFCP restarted [3906261591<3906261733] in Heartbeat REQ (../lib/pfcp/handler.c:39)
10/14 01:42:13.721: [upf] ERROR: PFCP restoration (../src/upf/pfcp-sm.c:238)
10/14 01:53:15.676: [upf] WARNING: PFCP[REQ] has already been associated [127.0.0.1]:8805 (../src/upf/pfcp-sm.c:270)
10/14 01:53:15.677: [pfcp] ERROR: Remote PFCP restarted [3906261733<3906262395] in Heartbeat REQ (../lib/pfcp/handler.c:39)
10/14 01:53:15.678: [upf] ERROR: PFCP restoration (../src/upf/pfcp-sm.c:238)
10/14 01:53:21.782: [pfcp] WARNING: [1] REMOTE Request Duplicated. Retransmit! for step 2 type 5 peer [127.0.0.1]:8805 (../lib/pfcp/xact.c:384)
10/14 01:53:21.784: [pfcp] ERROR: Remote PFCP restarted [3906262395<3906262401] in Heartbeat REQ (../lib/pfcp/handler.c:39)
10/14 01:53:21.784: [upf] ERROR: PFCP restoration (../src/upf/pfcp-sm.c:238)
10/14 01:53:22.795: [pfcp] WARNING: [74] LOCAL  No Reponse. Give up! for step 1 type 1 peer [127.0.0.1]:8805 (../lib/pfcp/xact.c:599)
10/14 01:53:22.795: [upf] WARNING: No Heartbeat from SMF [127.0.0.1]:8805 (../src/upf/pfcp-sm.c:329)
10/14 01:53:22.795: [upf] INFO: PFCP de-associated [127.0.0.1]:8805 (../src/upf/pfcp-sm.c:199)
10/14 03:06:24.871: [upf] INFO: PFCP associated [127.0.0.1]:8805 (../src/upf/pfcp-sm.c:184)
10/14 03:06:24.872: [pfcp] ERROR: Remote PFCP restarted [3906262401<3906266784] in Heartbeat REQ (../lib/pfcp/handler.c:39)
10/14 03:06:24.872: [upf] ERROR: PFCP restoration (../src/upf/pfcp-sm.c:238)
10/14 03:07:49.418: [pfcp] WARNING: [82] LOCAL  No Reponse. Give up! for step 1 type 1 peer [127.0.0.1]:8805 (../lib/pfcp/xact.c:599)
10/14 03:07:49.418: [upf] WARNING: No Heartbeat from SMF [127.0.0.1]:8805 (../src/upf/pfcp-sm.c:329)
10/14 03:07:49.418: [upf] INFO: PFCP de-associated [127.0.0.1]:8805 (../src/upf/pfcp-sm.c:199)
10/14 03:07:53.871: [upf] INFO: PFCP associated [127.0.0.1]:8805 (../src/upf/pfcp-sm.c:184)
10/14 03:07:53.872: [pfcp] ERROR: Remote PFCP restarted [3906266784<3906266873] in Heartbeat REQ (../lib/pfcp/handler.c:39)
10/14 03:07:53.872: [upf] ERROR: PFCP restoration (../src/upf/pfcp-sm.c:238)
10/14 03:09:54.722: [pfcp] INFO: ogs_pfcp_connect() [127.0.0.1]:2231 (../lib/pfcp/path.c:61)
10/14 03:09:54.722: [upf] INFO: PFCP associated [127.0.0.1]:2231 (../src/upf/pfcp-sm.c:184)
